name: Lint Checker

# Run on PRs and on pushes to main/develop
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  lint:
    name: 🔍 ESLint & TS‑Check
    runs-on: ubuntu-latest
    steps:
      # 1. Fetch your code
      - uses: actions/checkout@v4

      # 2. Install Node (v18)
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      # 3. Install deps (uses cache automatically thanks to setup-node@v4 cache: 'npm')
      - name: Install dependencies
        run: npm ci

      # 4. Run ESLint
      - name: Run ESLint
        run: npm run lint

      # 5. (Optional) Type‑check without emit
      - name: Run TypeScript compiler
        run: npx tsc --noEmit
